###############################################################################################
#
# NPI activity “Stochastic Modelling of Atmospheric Re-entry Highly Energetic Break-up Events”
# Fragmentation model
#
#Goal: prediction of the masses of fragments, given observed or synthetic data.
################################################################################################
rm(list=ls(all=TRUE)) #Clearing Console

library(igraph)
#library(xtable) # to use for the generation of latex tables
library(MASS) 
library(MCMCpack)
library(coda)
library(Rlab)
library(ggplot2) #to generate plots

#-------------------------------------------------------------------------------------------------------------------------
#Input variables
n.leaves<-15 #number of fragments. Default:15 
#Constraint: n.leaves<1+height_tree*(deg1-1)*deg2
#Tree-structure constraints (for further details see section 6.5.1 of the thesis )
height_tree<-4  #number of edges of the central path. Default:4                                       
deg1<-5   #maximum out-degree of the nodes of the central path. Default: 5                              
deg2<-4  #maximum out-degree of the nodes within distance 1 of the central path. Default: 4         
alpha<-1000 #scalar concentration parameter. Default: 1000 (to avoid zeros from rdirichlet)
alpha.data<-0 #splitting proportions vector. Default:0 
#For the generation of synthetic data
k<-2 #number of observations. Default:2
prob_observed<-0.5 # probability for each fragment of being observed (assumed constant). Default:0.5
niterations<-3000 #number of iterations of the Gibbs sampler. Default:3000
#
#
#--------------------------------------------------------------------------------------------------------------------------
source("Tree-structure generator.R")
source("Generate synthetic data.R")
source("Gibbs sampler for the inference.R")
source("Masses prediction.R")

#############################################################################################

#Save the outcomes
save(expecteddata, file="predictedmasses.RData") #masses with confidence interval
save(memorize.mu, file="musyntheticdata.RData") #values of the splitting proportions vector generated by the Gibbs sampler
save(memorize.vec.alpha, file= "iterationsalpha.RData") #values of the alpha parameter generated by the Gibbs sampler

#Examples of plots for the assessment of the MCMC convergence

#Plot in a pdf file the results of the Gibbs sampler iterations for the first two elements of the splitting proportions vector. The red line is the true value: the value used to generate the synthetic data. This plots can be used to verify the convergence of the MCMC algorithm.
# pdf(file="mu-syntheticdata.pdf",height=30,width=20)
# par(mfrow=c(2,1),cex="3")
# plot(1:(niterations+1),memorize.mu[,1],type='l',xlab='iteration', ylab=expression(""*mu[1]*""))
# lines(1:(niterations+1), rep(alpha.data[1],(niterations+1)), type="l", col="red") 
# plot(1:(niterations+1),memorize.mu[,2],type='l',xlab='iteration', ylab=expression(""*mu[2]*""))
# lines(1:(niterations+1), rep(alpha.data[2],(niterations+1)), type="l", col="red")
# dev.off()

#Plot in a pdf file the results of the Gibbs sampler iterations for the first two elements of the alpha vector. The red line is the true value: the value used to generate the synthetic data. This plots can be used to verify the convergence of the MCMC algorithm.

# pdf(file="iterationsalpha.pdf",height=30,width=22)
# par(mfrow=c(2,1), cex="2")
# plot(1:(niterations+1),memorize.vec.alpha[,1],type='l',xlab='iteration',ylab=expression(""*alpha[1]*""))
# lines(1:(niterations+1), rep(truealphavalues[1],(niterations+1)), type="l", col="red")
# plot(1:(niterations+1),memorize.vec.alpha[,2],type='l',xlab='iteration', ylab=expression(""*alpha[2]*""))
# lines(1:(niterations+1), rep(truealphavalues[2],(niterations+1)), type="l", col="red")
# dev.off()


